import { supabase } from '../supabaseClient';

export interface AnalyticsData { overview: { totalUsers: number; activeUsers: number; newUsers: number; engagement: number; retention: number; growth: number; }; traffic: { pageViews: number; uniqueVisitors: number; bounceRate: number; avgSessionTime: number; topPages: Array<{ page: string; views: number; growth: number }>; }; engagement: { postsCreated: number; commentsCount: number; likesCount: number; sharesCount: number; avgEngagement: number; topContent: Array<{ title: string; engagement: number; type: string }>; }; demographics: { byCourse: Array<{ course: string; users: number; percentage: number }>; byYear: Array<{ year: string; users: number; percentage: number }>; byUniversity: Array<{ university: string; users: number; percentage: number }>; byDevice: Array<{ device: string; users: number; percentage: number }>; }; realTime: { onlineUsers: number; activeSessions: number; currentActivity: Array<{ user: string; action: string; time: string }>; }; }

const exact = async (table: string, column = 'id') => { const { count, error } = await supabase.from(table).select(column, { count: 'exact', head: true }); if (error) throw error; return count || 0; };
export class AnalyticsService {
  static async getAnalyticsData(timeRange: '24h'|'7d'|'30d'|'90d'): Promise<AnalyticsData> {
    const [totalUsers, postsCreated, commentsCount] = await Promise.all([exact('profiles'), exact('posts'), exact('comments')]);
    const { data: profiles } = await supabase.from('profiles').select('course, year, university');
    const countValues = (key: 'course'|'year'|'university') => { const map = new Map<string, number>(); (profiles || []).forEach(row => { const value = String(row[key] || 'Não informado'); map.set(value, (map.get(value) || 0) + 1); }); return Array.from(map.entries()).map(([value, users]) => ({ [key]: value, users, percentage: totalUsers ? Math.round(users / totalUsers * 10000) / 100 : 0 })); };
    return { overview: { totalUsers, activeUsers: 0, newUsers: 0, engagement: totalUsers ? Math.round(postsCreated / totalUsers * 10000) / 100 : 0, retention: 0, growth: 0 }, traffic: { pageViews: 0, uniqueVisitors: 0, bounceRate: 0, avgSessionTime: 0, topPages: [] }, engagement: { postsCreated, commentsCount, likesCount: 0, sharesCount: 0, avgEngagement: postsCreated ? commentsCount / postsCreated : 0, topContent: [] }, demographics: { byCourse: countValues('course') as any, byYear: countValues('year') as any, byUniversity: countValues('university') as any, byDevice: [] }, realTime: { onlineUsers: 0, activeSessions: 0, currentActivity: [] } };
  }
}
