import { supabase } from '../supabaseClient';

export interface UserProfile { uid: string; email: string; displayName: string; photoURL?: string; userType: 'aluno'|'professor'|'uni'; registrationNumber: string; university: string; course: string; year: number; period: number; bio?: string; interests: string[]; isVerified: boolean; onboardingCompleted: boolean; createdAt: string; updatedAt: string; }

const mapProfile = (row: any): UserProfile => ({ uid: row.id, email: row.email || '', displayName: row.display_name || 'Usuário', photoURL: row.photo_url || '', userType: row.user_type || 'aluno', registrationNumber: row.registration_number || '', university: row.university || 'Universidade não informada', course: row.course || 'Curso não informado', year: row.year || 2026, period: row.period || 1, bio: row.bio || '', interests: row.interests || [], isVerified: Boolean(row.is_verified), onboardingCompleted: Boolean(row.onboarding_completed), createdAt: row.created_at || '', updatedAt: row.updated_at || '' });

export const registerUser = async (email: string, password: string, displayName: string, registrationNumber: string, university: string, course: string, year: number, period: number, userType: 'aluno'|'professor'|'uni' = 'aluno') => { const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { displayName, registrationNumber, university, course, year: Number(year), period: Number(period), userType } } }); if (error) throw error; return { user: { uid: data.user?.id, email: data.user?.email, displayName, emailVerified: Boolean(data.user?.email_confirmed_at) } }; };
export const loginUser = async (email: string, password: string) => { const { data, error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw error; return { user: { uid: data.user.id, email: data.user.email, displayName: data.user.user_metadata?.displayName || '', emailVerified: true } }; };
export const loginWithRegistration = async (registrationNumber: string, password: string) => { const { data, error } = await supabase.from('profiles').select('email').eq('registration_number', registrationNumber).single(); if (error || !data) throw new Error('Matrícula não encontrada'); return loginUser(data.email, password); };
export const getUserByRegistration = async (registrationNumber: string): Promise<UserProfile|null> => { const { data } = await supabase.from('profiles').select('*').eq('registration_number', registrationNumber).maybeSingle(); return data ? mapProfile(data) : null; };
export const logoutUser = async () => { const { error } = await supabase.auth.signOut(); if (error) throw error; };
export const resetPassword = async (email: string) => { const baseUrl = process.env.REACT_APP_SITE_URL?.trim() || window.location.origin; const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: new URL('/reset-password', baseUrl).toString() }); if (error) throw error; };
export const getUserProfile = async (uid: string): Promise<UserProfile|null> => { const { data, error } = await supabase.from('profiles').select('*').eq('id', uid).single(); if (error || !data) return null; return mapProfile(data); };
export const updateUserProfile = async (uid: string, updates: Partial<UserProfile>) => { const dbUpdates: any = {}; if (updates.displayName !== undefined) dbUpdates.display_name = updates.displayName; if (updates.photoURL !== undefined) dbUpdates.photo_url = updates.photoURL; if (updates.userType !== undefined) dbUpdates.user_type = updates.userType; if (updates.registrationNumber !== undefined) dbUpdates.registration_number = updates.registrationNumber; if (updates.university !== undefined) dbUpdates.university = updates.university; if (updates.course !== undefined) dbUpdates.course = updates.course; if (updates.year !== undefined) dbUpdates.year = Number(updates.year); if (updates.period !== undefined) dbUpdates.period = Number(updates.period); if (updates.bio !== undefined) dbUpdates.bio = updates.bio; if (updates.interests !== undefined) dbUpdates.interests = updates.interests; if (updates.isVerified !== undefined) dbUpdates.is_verified = updates.isVerified; if (updates.onboardingCompleted !== undefined) dbUpdates.onboarding_completed = updates.onboardingCompleted; const { error } = await supabase.from('profiles').update(dbUpdates).eq('id', uid); if (error) throw error; };
export const isInstitutionalEmail = (email: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
